language: python
python:
    - "3.6"
install:
    - pip install python-coveralls pytest-cov
    - pip install .
script: 
    - py.test tests --cov shortest_functional_protein
after_success:
    - coveralls
